---
titulo: Fórmula de la media y la serie geométrica, tesis de ejemplo
autor: PACHÁ
nombrecompleto: SIMPLEMENTE PACHÁ
escuelaodepartamento: Departamento de Estadística
facultad: Facultad de Derecho
tituloogrado: Magíster en Estadística
profesorguia: Nombre del profesor guía
miembrocomite1: Nombre del miembro del comité 1
miembrocomite2: Nombre del miembro del comité 2
miembroinvitadocomite1: Nombre del miembro invitado del comité 1
miembroinvitadocomite2: Nombre del miembro invitado del comité 2
representantedipei: Nombre del representante DIPEI
materia: Estimación de parámetros
fecha: Diciembre 2019
anioromano: MMXIX
dedicatoria: A mi familia, amigos y personas valiosas de la universidad
output: 
  pdf_document:
    latex_engine: pdflatex
    template: formato-puc.tex
    keep_tex: yes
bibliography: bibliografia.bib
formatearbibliografia: true
link-references: true
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r child = 'capitulos/cap1-ejemplo.Rmd', eval = T}
```

```{r child = 'capitulos/cap2-ejemplo.Rmd', eval = T}
```

\appendix

```{r child = 'capitulos/apendice-ejemplo.Rmd', eval = T}
```
