\chapter{Efficient Fitting of Linear Models}

# Bottlenecks in GLM estimation

Besides the classic estimation problem of linear dependence when using fixed effects, which leads to `NA` estimated country-time specific coefficients, the estimation of relevant effects such as RTAs over time constitutes itself a bottle neck which is not solved necessarily by scaling hardware.

<!-- Certainly, more powerful processors allow a faster estimation for some statistical models, but fitting times are very consistent on scaled hardware, so a solution for competitive fitting times is related to a different fitting algorithm. -->

Reproducing the traditional gravity estimates PPML model from Chapter 1 in @yotov2016advanced was already discussed in the previous chapter of this thesis, and an interesting model with country-time fixed effects and Quasi-Poisson link is
\begin{align*}
X_{ij,t} =& \:\exp\left[\pi_{i,t} + \chi_{i,t} + \beta_1 \log(DIST)_{i,j} + \beta_2 CNTG_{i,j} +\right.\\
\text{ }& \:\left.\beta_3 LANG_{i,j} + \beta_4 CLNY_{i,j}\right] \times \varepsilon_{ij,t}
\end{align*}

To compare GLM vs the proposed Efficient-GLM (EGLM) function, I conducted a test with 500 repetitions locally.

```{r, echo=FALSE, fig.height=3, fig.width=5, message=FALSE, warning=FALSE, dpi=75}
g <- readRDS("../benchmarks/04-stata-vs-r.rda")
g
```
